package danger.orespawn.init;

import net.minecraft.block.*;
import java.util.*;
import danger.orespawn.blocks.*;

public class ModBlocks
{
    public static final List<Block> BLOCKS;
    public static final Block CORN_PLANT;
    public static final Block BUTTERFLY_PLANT;
    public static final Block MOSQUITO_PLANT;
    public static final Block FIREFLY_PLANT;
    public static final Block MOTH_PLANT;
    public static final Block URANIUM_BLOCK;
    public static final Block TITANIUM_BLOCK;
    public static final Block URANIUM_ORE;
    public static final Block TITANIUM_ORE;
    public static final Block ANT_BLOCK;
    public static final Block ALOSAURUS_ORE;
    public static final Block BARYONYX_ORE;
    public static final Block CAMARASAURUS_ORE;
    public static final Block CRYOLOPHOSAURUS_ORE;
    public static final Block POINTYSAURUS_ORE;
    public static final Block TREX_ORE;
    public static final Block COW_ORE;
    public static final Block CREEPER_ORE;
    public static final Block GHAST_ORE;
    public static final Block HORSE_ORE;
    public static final Block PIG_ORE;
    public static final Block ZOMBIE_ORE;
    public static final Block BIRD_ORE;
    public static final Block ALIEN_ORE;
    public static final Block CAVEFISHER_ORE;
    public static final Block NASTYSAURUS_ORE;
    public static final Block VELOCITYRAPTOR_ORE;
    public static final Block WTF_ORE;
    public static final Block SPYRO_ORE;
    public static final Block DRAGONFLY_ORE;
    public static final Block EXTREME_TORCH;
    public static final Block SMALLWORM_ORE;
    public static final Block MEDIUMWORM_ORE;
    public static final Block LARGEWORM_ORE;
    public static final Block DOOMWORM_ORE;
    public static final Block RED_ANT_TROLL_BLOCK;
    public static final Block MANTIS_ORE;
    public static final Block BEAVER_ORE;
    public static final Block BRUTALFLY_ORE;
    public static final Block KYUUBI_ORE;
    public static final Block MOTHRA_ORE;
    public static final Block AMETHYST_ORE;
    public static final Block AMETHYST_BLOCK;
    public static final Block CASSOWARY_ORE;
    public static final Block REDCOW_ORE;
    public static final Block STINKBUG_ORE;
    
    static {
        BLOCKS = new ArrayList<Block>();
        CORN_PLANT = new BlockCornPlant();
        BUTTERFLY_PLANT = (Block)new BlockButterflyPlant();
        MOSQUITO_PLANT = (Block)new BlockMosquitoPlant();
        FIREFLY_PLANT = (Block)new BlockFireflyPlant();
        MOTH_PLANT = (Block)new BlockMothPlant();
        URANIUM_BLOCK = new BlockUranium();
        TITANIUM_BLOCK = new BlockTitanium();
        URANIUM_ORE = new OreUranium();
        TITANIUM_ORE = new OreTitanium();
        ANT_BLOCK = new BlockAnt();
        ALOSAURUS_ORE = new OreGenericEgg("alosaurus_ore");
        BARYONYX_ORE = new OreGenericEgg("baryonyx_ore");
        CAMARASAURUS_ORE = new OreGenericEgg("camarasaurus_ore");
        CRYOLOPHOSAURUS_ORE = new OreGenericEgg("cryolophosaurus_ore");
        POINTYSAURUS_ORE = new OreGenericEgg("pointysaurus_ore");
        TREX_ORE = new OreGenericEgg("trex_ore");
        COW_ORE = new OreGenericEgg("cow_ore");
        CREEPER_ORE = new OreGenericEgg("creeper_ore");
        GHAST_ORE = new OreGenericEgg("ghast_ore");
        HORSE_ORE = new OreGenericEgg("horse_ore");
        PIG_ORE = new OreGenericEgg("pig_ore");
        ZOMBIE_ORE = new OreGenericEgg("zombie_ore");
        BIRD_ORE = new OreGenericEgg("bird_ore");
        ALIEN_ORE = new OreGenericEgg("alien_ore");
        CAVEFISHER_ORE = new OreGenericEgg("cavefisher_ore");
        NASTYSAURUS_ORE = new OreGenericEgg("nastysaurus_ore");
        VELOCITYRAPTOR_ORE = new OreGenericEgg("velocityraptor_ore");
        WTF_ORE = new OreGenericEgg("gammametroid_ore");
        SPYRO_ORE = new OreGenericEgg("spyro_ore");
        DRAGONFLY_ORE = new OreGenericEgg("dragonfly_ore");
        EXTREME_TORCH = (Block)new BlockExtremeTorch();
        SMALLWORM_ORE = new OreGenericEgg("smallworm_ore");
        MEDIUMWORM_ORE = new OreGenericEgg("mediumworm_ore");
        LARGEWORM_ORE = new OreGenericEgg("largeworm_ore");
        DOOMWORM_ORE = new OreGenericEgg("doomworm_ore");
        RED_ANT_TROLL_BLOCK = new BlockRedAntTroll();
        MANTIS_ORE = new OreGenericEgg("mantis_ore");
        BEAVER_ORE = new OreGenericEgg("beaver_ore");
        BRUTALFLY_ORE = new OreGenericEgg("brutalfly_ore");
        KYUUBI_ORE = new OreGenericEgg("kyuubi_ore");
        MOTHRA_ORE = new OreGenericEgg("mothra_ore");
        AMETHYST_ORE = new OreAmethyst();
        AMETHYST_BLOCK = new BlockAmethyst();
        CASSOWARY_ORE = new OreGenericEgg("cassowary_ore");
        REDCOW_ORE = new OreGenericEgg("redcow_ore");
        STINKBUG_ORE = new OreGenericEgg("stinkbug_ore");
    }
}
