package danger.orespawn.init;

import net.minecraft.item.*;
import java.util.*;
import net.minecraft.entity.*;
import net.minecraft.entity.passive.*;
import net.minecraft.entity.monster.*;
import net.minecraft.inventory.*;
import danger.orespawn.items.armor.*;
import danger.orespawn.items.tools.*;
import danger.orespawn.items.food.*;
import danger.orespawn.items.*;
import danger.orespawn.entity.*;

public class ModItems
{
    public static final List<Item> ITEMS;
    public static final Item URANIUM_NUGGET;
    public static final Item TITANIUM_NUGGET;
    public static final Item URANIUM_INGOT;
    public static final Item TITANIUM_INGOT;
    public static final Item TREX_TOOTH;
    public static final Item EMPTY_CAGE;
    public static final Item ALOSAURUS_CAGE;
    public static final Item TREX_CAGE;
    public static final Item COW_CAGE;
    public static final Item CREEPER_CAGE;
    public static final Item GHAST_CAGE;
    public static final Item HORSE_CAGE;
    public static final Item PIG_CAGE;
    public static final Item ZOMBIE_CAGE;
    public static final Item GAMMAMETROID_CAGE;
    public static final Item SPYRO_CAGE;
    public static final Item DRAGONFLY_CAGE;
    public static final Item FIREFLY_CAGE;
    public static final Item NASTYSAURUS_CAGE;
    public static final Item ALIEN_CAGE;
    public static final Item VELOCITYRAPTOR_CAGE;
    public static final Item ULTIMATE_HELMET;
    public static final Item ULTIMATE_CHESTPLATE;
    public static final Item ULTIMATE_LEGGINGS;
    public static final Item ULTIMATE_BOOTS;
    public static final Item EMERALD_HELMET;
    public static final Item EMERALD_CHESTPLATE;
    public static final Item EMERALD_LEGGINGS;
    public static final Item EMERALD_BOOTS;
    public static final Item ULTIMATE_PICKAXE;
    public static final Item ULTIMATE_SWORD;
    public static final Item ULTIMATE_AXE;
    public static final Item ULTIMATE_SHOVEL;
    public static final Item ULTIMATE_HOE;
    public static final Item EMERALD_PICKAXE;
    public static final Item EMERALD_SWORD;
    public static final Item EMERALD_AXE;
    public static final Item EMERALD_SHOVEL;
    public static final Item EMERALD_HOE;
    public static final Item AMETHYST_PICKAXE;
    public static final Item AMETHYST_SWORD;
    public static final Item AMETHYST_AXE;
    public static final Item AMETHYST_SHOVEL;
    public static final Item AMETHYST_HOE;
    public static final Item CORN;
    public static final Item BUTTERFLY_SEED;
    public static final Item MOSQUITO_SEED;
    public static final Item FIREFLY_SEED;
    public static final Item MOTH_SEED;
    public static final Item ALOSAURUS_EGG;
    public static final Item BARYONYX_EGG;
    public static final Item CAMARASAURUS_EGG;
    public static final Item CRYOLOPHOSAURUS_EGG;
    public static final Item POINTYSAURUS_EGG;
    public static final Item TREX_EGG;
    public static final Item CAVEFISHER_EGG;
    public static final Item BUTTERFLY_EGG;
    public static final Item BIRD_EGG;
    public static final Item RED_ANT_EGG;
    public static final Item GAMMAMETROID_EGG;
    public static final Item SPYRO_EGG;
    public static final Item DRAGONFLY_EGG;
    public static final Item FIREFLY_EGG;
    public static final Item MOSQUITO_EGG;
    public static final Item NASTYSAURUS_EGG;
    public static final Item ALIEN_EGG;
    public static final Item VELOCITYRAPTOR_EGG;
    public static final Item WORM_TOOTH;
    public static final Item WORM_FOOD;
    public static final Item SMALLWORM_EGG;
    public static final Item MEDIUMWORM_EGG;
    public static final Item LARGEWORM_EGG;
    public static final Item DOOMWORM_EGG;
    public static final Item SMALLWORM_CAGE;
    public static final Item MEDIUMWORM_CAGE;
    public static final Item LARGEWORM_CAGE;
    public static final Item MOTH_EGG;
    public static final Item KYUUBI_EGG;
    public static final Item MANTIS_EGG;
    public static final Item MONTHRA_EGG;
    public static final Item BRUTALFLY_EGG;
    public static final Item BEAVER_EGG;
    public static final Item KYUUBI_CAGE;
    public static final Item MANTIS_CAGE;
    public static final Item MONTHRA_CAGE;
    public static final Item BRUTALFLY_CAGE;
    public static final Item BEAVER_CAGE;
    public static final Item MOTH_SCALE;
    public static final Item MANTIS_CLAW;
    public static final Item MOTH_HELMET;
    public static final Item MOTH_CHESTPLATE;
    public static final Item MOTH_LEGGINGS;
    public static final Item MOTH_BOOTS;
    public static final Item AMETHYST_HELMET;
    public static final Item AMETHYST_CHESTPLATE;
    public static final Item AMETHYST_LEGGINGS;
    public static final Item AMETHYST_BOOTS;
    public static final Item AMETHYST;
    public static final Item TERMITE_EGG;
    public static final Item CASSOWARY_EGG;
    public static final Item REDCOW_EGG;
    public static final Item STINKBUG_EGG;
    public static final Item REDCOW_CAGE;
    public static final Item STINKBUG_CAGE;
    public static final Item CASSOWARY_CAGE;
    
    static {
        ITEMS = new ArrayList<Item>();
        URANIUM_NUGGET = new ItemBasic("uranium_nugget");
        TITANIUM_NUGGET = new ItemBasic("titanium_nugget");
        URANIUM_INGOT = new ItemBasic("uranium_ingot");
        TITANIUM_INGOT = new ItemBasic("titanium_ingot");
        TREX_TOOTH = new ItemBasic("trextooth");
        EMPTY_CAGE = new CritterCage(null, "empty_cage");
        ALOSAURUS_CAGE = new CritterCage((Class<? extends Entity>)Alosaurus.class, "alosaurus_cage", 0.4f);
        TREX_CAGE = new CritterCage((Class<? extends Entity>)TRex.class, "trex_cage", 0.4f);
        COW_CAGE = new CritterCage((Class<? extends Entity>)EntityCow.class, "cow_cage", 0.4f);
        CREEPER_CAGE = new CritterCage((Class<? extends Entity>)EntityCreeper.class, "creeper_cage", 0.4f);
        GHAST_CAGE = new CritterCage((Class<? extends Entity>)EntityGhast.class, "ghast_cage", 0.4f);
        HORSE_CAGE = new CritterCage((Class<? extends Entity>)EntityHorse.class, "horse_cage", 0.4f);
        PIG_CAGE = new CritterCage((Class<? extends Entity>)EntityPig.class, "pig_cage", 0.4f);
        ZOMBIE_CAGE = new CritterCage((Class<? extends Entity>)EntityZombie.class, "zombie_cage", 0.4f);
        GAMMAMETROID_CAGE = new CritterCage((Class<? extends Entity>)GammaMetroid.class, "gammametroid_cage", 0.4f);
        SPYRO_CAGE = new CritterCage((Class<? extends Entity>)Spyro.class, "spyro_cage", 0.4f);
        DRAGONFLY_CAGE = new CritterCage((Class<? extends Entity>)Dragonfly.class, "dragonfly_cage", 0.4f);
        FIREFLY_CAGE = new CritterCage((Class<? extends Entity>)Firefly.class, "firefly_cage", 0.4f);
        NASTYSAURUS_CAGE = new CritterCage((Class<? extends Entity>)Nastysaurus.class, "nastysaurus_cage", 0.4f);
        ALIEN_CAGE = new CritterCage((Class<? extends Entity>)Alien.class, "alien_cage", 0.4f);
        VELOCITYRAPTOR_CAGE = new CritterCage((Class<? extends Entity>)VelocityRaptor.class, "velocityraptor_cage", 0.4f);
        ULTIMATE_HELMET = (Item)new ArmorBase("ultimate_helmet", OrespawnArmorMaterial.UltimateArmor, EntityEquipmentSlot.HEAD);
        ULTIMATE_CHESTPLATE = (Item)new ArmorBase("ultimate_chestplate", OrespawnArmorMaterial.UltimateArmor, EntityEquipmentSlot.CHEST);
        ULTIMATE_LEGGINGS = (Item)new ArmorBase("ultimate_leggings", OrespawnArmorMaterial.UltimateArmor, EntityEquipmentSlot.LEGS);
        ULTIMATE_BOOTS = (Item)new ArmorBase("ultimate_boots", OrespawnArmorMaterial.UltimateArmor, EntityEquipmentSlot.FEET);
        EMERALD_HELMET = (Item)new ArmorBase("emerald_helmet", OrespawnArmorMaterial.EmeraldArmor, EntityEquipmentSlot.HEAD);
        EMERALD_CHESTPLATE = (Item)new ArmorBase("emerald_chestplate", OrespawnArmorMaterial.EmeraldArmor, EntityEquipmentSlot.CHEST);
        EMERALD_LEGGINGS = (Item)new ArmorBase("emerald_leggings", OrespawnArmorMaterial.EmeraldArmor, EntityEquipmentSlot.LEGS);
        EMERALD_BOOTS = (Item)new ArmorBase("emerald_boots", OrespawnArmorMaterial.EmeraldArmor, EntityEquipmentSlot.FEET);
        ULTIMATE_PICKAXE = (Item)new UltimatePickaxe();
        ULTIMATE_SWORD = (Item)new UltimateSword();
        ULTIMATE_AXE = (Item)new UltimateAxe();
        ULTIMATE_SHOVEL = (Item)new UltimateShovel();
        ULTIMATE_HOE = (Item)new UltimateHoe();
        EMERALD_PICKAXE = (Item)new EmeraldPickaxe();
        EMERALD_SWORD = (Item)new EmeraldSword();
        EMERALD_AXE = (Item)new EmeraldAxe();
        EMERALD_SHOVEL = (Item)new EmeraldShovel();
        EMERALD_HOE = (Item)new EmeraldHoe();
        AMETHYST_PICKAXE = (Item)new GenericPickaxe("amethyst_pickaxe", OrespawnToolMaterial.AmethystTools);
        AMETHYST_SWORD = (Item)new GenericSword("amethyst_sword", OrespawnToolMaterial.AmethystTools);
        AMETHYST_AXE = (Item)new GenericAxe("amethyst_axe", OrespawnToolMaterial.AmethystTools);
        AMETHYST_SHOVEL = (Item)new GenericShovel("amethyst_shovel", OrespawnToolMaterial.AmethystTools);
        AMETHYST_HOE = (Item)new GenericHoe("amethyst_hoe", OrespawnToolMaterial.AmethystTools);
        CORN = (Item)new ItemCorn();
        BUTTERFLY_SEED = new ItemButterflySeed();
        MOSQUITO_SEED = new ItemMosquitoSeed();
        FIREFLY_SEED = new ItemFireflySeed();
        MOTH_SEED = new ItemMothSeed();
        ALOSAURUS_EGG = new ItemGenericEgg("alosaurus_egg", (Class<? extends Entity>)Alosaurus.class);
        BARYONYX_EGG = new ItemGenericEgg("baryonyx_egg", (Class<? extends Entity>)Baryonyx.class);
        CAMARASAURUS_EGG = new ItemGenericEgg("camarasaurus_egg", (Class<? extends Entity>)Camarasaurus.class);
        CRYOLOPHOSAURUS_EGG = new ItemGenericEgg("cryolophosaurus_egg", (Class<? extends Entity>)Cryolophosaurus.class);
        POINTYSAURUS_EGG = new ItemGenericEgg("pointysaurus_egg", (Class<? extends Entity>)Pointysaurus.class);
        TREX_EGG = new ItemGenericEgg("trex_egg", (Class<? extends Entity>)TRex.class);
        CAVEFISHER_EGG = new ItemGenericEgg("cavefisher_egg", (Class<? extends Entity>)CaveFisher.class);
        BUTTERFLY_EGG = new ItemGenericEgg("butterfly_egg", (Class<? extends Entity>)Butterfly.class);
        BIRD_EGG = new ItemGenericEgg("bird_egg", (Class<? extends Entity>)Bird.class);
        RED_ANT_EGG = new ItemGenericEgg("red_ant_egg", (Class<? extends Entity>)RedAnt.class);
        GAMMAMETROID_EGG = new ItemGenericEgg("gammametroid_egg", (Class<? extends Entity>)GammaMetroid.class);
        SPYRO_EGG = new ItemGenericEgg("spyro_egg", (Class<? extends Entity>)Spyro.class);
        DRAGONFLY_EGG = new ItemGenericEgg("dragonfly_egg", (Class<? extends Entity>)Dragonfly.class);
        FIREFLY_EGG = new ItemGenericEgg("firefly_egg", (Class<? extends Entity>)Firefly.class);
        MOSQUITO_EGG = new ItemGenericEgg("mosquito_egg", (Class<? extends Entity>)Mosquito.class);
        NASTYSAURUS_EGG = new ItemGenericEgg("nastysaurus_egg", (Class<? extends Entity>)Nastysaurus.class);
        ALIEN_EGG = new ItemGenericEgg("alien_egg", (Class<? extends Entity>)Alien.class);
        VELOCITYRAPTOR_EGG = new ItemGenericEgg("velocityraptor_egg", (Class<? extends Entity>)VelocityRaptor.class);
        WORM_TOOTH = new ItemBasic("worm_tooth");
        WORM_FOOD = new ItemBasic("worm_food");
        SMALLWORM_EGG = new ItemGenericEgg("smallworm_egg", (Class<? extends Entity>)WormSmall.class);
        MEDIUMWORM_EGG = new ItemGenericEgg("mediumworm_egg", (Class<? extends Entity>)WormMedium.class);
        LARGEWORM_EGG = new ItemGenericEgg("largeworm_egg", (Class<? extends Entity>)WormLarge.class);
        DOOMWORM_EGG = new ItemGenericEgg("doomworm_egg", (Class<? extends Entity>)WormDoom.class);
        SMALLWORM_CAGE = new CritterCage((Class<? extends Entity>)WormSmall.class, "smallworm_cage", 0.4f);
        MEDIUMWORM_CAGE = new CritterCage((Class<? extends Entity>)WormMedium.class, "mediumworm_cage", 0.4f);
        LARGEWORM_CAGE = new CritterCage((Class<? extends Entity>)WormLarge.class, "largeworm_cage", 0.4f);
        MOTH_EGG = new ItemGenericEgg("moth_egg", (Class<? extends Entity>)Moth.class);
        KYUUBI_EGG = new ItemGenericEgg("kyuubi_egg", (Class<? extends Entity>)Kyuubi.class);
        MANTIS_EGG = new ItemGenericEgg("mantis_egg", (Class<? extends Entity>)Mantis.class);
        MONTHRA_EGG = new ItemGenericEgg("mothra_egg", (Class<? extends Entity>)Mothra.class);
        BRUTALFLY_EGG = new ItemGenericEgg("brutalfly_egg", (Class<? extends Entity>)Brutalfly.class);
        BEAVER_EGG = new ItemGenericEgg("beaver_egg", (Class<? extends Entity>)Beaver.class);
        KYUUBI_CAGE = new CritterCage((Class<? extends Entity>)Kyuubi.class, "kyuubi_cage", 0.4f);
        MANTIS_CAGE = new CritterCage((Class<? extends Entity>)Mantis.class, "mantis_cage", 0.4f);
        MONTHRA_CAGE = new CritterCage((Class<? extends Entity>)Mothra.class, "mothra_cage", 0.4f);
        BRUTALFLY_CAGE = new CritterCage((Class<? extends Entity>)Brutalfly.class, "brutalfly_cage", 0.4f);
        BEAVER_CAGE = new CritterCage((Class<? extends Entity>)Beaver.class, "beaver_cage", 0.4f);
        MOTH_SCALE = new ItemBasic("moth_scale");
        MANTIS_CLAW = new ItemBasic("mantis_claw");
        MOTH_HELMET = (Item)new ArmorBase("moth_helmet", OrespawnArmorMaterial.MothArmor, EntityEquipmentSlot.HEAD);
        MOTH_CHESTPLATE = (Item)new ArmorBase("moth_chestplate", OrespawnArmorMaterial.MothArmor, EntityEquipmentSlot.CHEST);
        MOTH_LEGGINGS = (Item)new ArmorBase("moth_leggings", OrespawnArmorMaterial.MothArmor, EntityEquipmentSlot.LEGS);
        MOTH_BOOTS = (Item)new ArmorBase("moth_boots", OrespawnArmorMaterial.MothArmor, EntityEquipmentSlot.FEET);
        AMETHYST_HELMET = (Item)new ArmorBase("amethyst_helmet", OrespawnArmorMaterial.AmethystArmor, EntityEquipmentSlot.HEAD);
        AMETHYST_CHESTPLATE = (Item)new ArmorBase("amethyst_chestplate", OrespawnArmorMaterial.AmethystArmor, EntityEquipmentSlot.CHEST);
        AMETHYST_LEGGINGS = (Item)new ArmorBase("amethyst_leggings", OrespawnArmorMaterial.AmethystArmor, EntityEquipmentSlot.LEGS);
        AMETHYST_BOOTS = (Item)new ArmorBase("amethyst_boots", OrespawnArmorMaterial.AmethystArmor, EntityEquipmentSlot.FEET);
        AMETHYST = new ItemBasic("amethyst");
        TERMITE_EGG = new ItemGenericEgg("termite_egg", (Class<? extends Entity>)Termite.class);
        CASSOWARY_EGG = new ItemGenericEgg("cassowary_egg", (Class<? extends Entity>)Cassowary.class);
        REDCOW_EGG = new ItemGenericEgg("redcow_egg", (Class<? extends Entity>)RedCow.class);
        STINKBUG_EGG = new ItemGenericEgg("stinkbug_egg", (Class<? extends Entity>)StinkBug.class);
        REDCOW_CAGE = new CritterCage((Class<? extends Entity>)RedCow.class, "redcow_cage", 0.4f);
        STINKBUG_CAGE = new CritterCage((Class<? extends Entity>)StinkBug.class, "stinkbug_cage", 0.4f);
        CASSOWARY_CAGE = new CritterCage((Class<? extends Entity>)Cassowary.class, "cassowary_cage", 0.4f);
    }
}
